/* Stitch 디자인 시스템 Tailwind 설정 — CDN 스크립트 뒤에서 로드됩니다. */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#42474e",
        "tertiary-container": "#3c3e3e",
        "surface-container": "#ededf2",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#9ccbfb",
        "surface-container-low": "#f3f3f7",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#004d62",
        "on-background": "#1a1c1f",
        "primary-container": "#00416a",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001d33",
        "surface-container-highest": "#e2e2e6",
        "surface-tint": "#31628d",
        "on-primary-container": "#7faddc",
        "on-tertiary-container": "#a8a9a9",
        "surface-dim": "#d9dade",
        "inverse-surface": "#2e3034",
        "secondary-fixed": "#baeaff",
        "inverse-on-surface": "#f0f0f4",
        "primary": "#002a48",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9fd",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#114a73",
        "secondary-container": "#9ae1ff",
        "secondary": "#0c6780",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e2e2e2",
        "outline": "#72777f",
        "tertiary": "#262829",
        "on-surface": "#1a1c1f",
        "surface": "#f9f9fd",
        "background": "#f9f9fd",
        "on-secondary-fixed": "#001f29",
        "on-secondary-container": "#09657f",
        "surface-container-high": "#e7e8ec",
        "primary-fixed": "#cfe5ff",
        "secondary-fixed-dim": "#89d0ed",
        "inverse-primary": "#9ccbfb",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e6",
        "outline-variant": "#c2c7cf",
        "on-tertiary-fixed-variant": "#454747",
        "safe-green": "#2e7d32",
        "warning-yellow": "#f9a825",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "container-max": "1280px",
        "stack-gap-md": "16px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-gap-lg": "32px",
      },
      fontFamily: {
        "display-lg": ["Pretendard"], "body-md": ["Pretendard"], "headline-lg": ["Pretendard"],
        "headline-lg-mobile": ["Pretendard"], "label-sm": ["Pretendard"], "title-md": ["Pretendard"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "700" }],
      },
    },
  },
};
